version: "3.8"

services:
  db:
    image: postgres:14
    container_name: mfa-postgres
    restart: always
    environment:
      POSTGRES_DB: mfa
      POSTGRES_USER: mfa_user
      POSTGRES_PASSWORD: mfa_pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: