spring:
  application:
    name: auth

  datasource:
    url: jdbc:postgresql://localhost:5432/mfa
    username: mfa_user
    password: mfa_pass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

server:
  port: 8081